spring:
  application:
    name: galtek-classroom-master-backend
  flyway:
    enabled: false

galtek:
  classroom:
    master:
      storage:
        enabled: true
        data-dir: ${GALTEK_CLASSROOM_MASTER_DATA_DIR:}
        database-file-name: classroom.db
        busy-timeout-ms: 5000
        maximum-pool-size: 4
        quick-check-on-startup: true
      network:
        grpc:
          enabled: false
          port: 9443
          heartbeat-timeout: 45s
          max-inbound-message-size: 65536

debug: false

logging:
  level:
    root: INFO

server:
  port: 8080
