package com.galtek.classroom.device;

public enum DeviceCapability {
    HEARTBEAT_V1,
    OPERATION_FRAMEWORK_V1,
    SESSION_AGENT_AVAILABLE,
    POWER_CONTROL_V1,
    OPEN_URL_V1,
    BROWSER_NAVIGATION_POLICY_V1,
    BROWSER_DOWNLOAD_POLICY_V1,
    LOCAL_IPC,
    SESSION_AGENT,
    APPLICATION_LAUNCH,
    BROWSER_LAUNCH,
    WORKSPACE_FILES,
    WALLPAPER,
    PROJECTION,
    INPUT_CONTROL
}
