package com.galtek.classroom.operations;

public enum OperationType {
    LOCK_INPUT,
    UNLOCK_INPUT,
    SHUTDOWN,
    RESTART,
    OPEN_APPLICATION,
    OPEN_URL,
    START_PROJECTION,
    STOP_PROJECTION,
    DISTRIBUTE_FILE,
    CREATE_FOLDER,
    SET_WALLPAPER,
    RESTORE_WALLPAPER,
    ASSIGN_STUDENT,
    MOVE_STUDENT,
    SWAP_STUDENTS,
    SYNC_STUDENT_WORKSPACE,
    RESTORE_STUDENT_WORKSPACE
}
